### ISSUE TITLE
[BUG] ParserError: Source file requires different compiler version

### ISSUE THREAD

**Issue by sjukeshov** [cleanunicorn/mythos#35]
**Describe the bug**
ParserError: Source file requires different compiler version

**To Reproduce**
1. https://github.com/ConsenSys/truffle-webpack-demo/blob/master/contracts/MetaCoin.sol
2. mythos analyze contracts/MetaCoin.sol MetaCoin
3. Error generated
 Error: contracts/ConvertLib.sol:2:1: ParserError: Source file requires different compiler version (current compiler is 0.5.6+commit.b259423e.Emscripten.clang - note that nightly builds are 
 ›   considered to be strictly less than the released version
 ›   library ConvertLib{
 ›   ^-----^
 ›

**Expected behavior**
No errors or issues found

**Console output**
```
mythos analyze contracts/MetaCoin.sol MetaCoin
Reading contract contracts/MetaCoin.sol... done
Compiling with Solidity version: v0.5.6+commit.b259423e
 ›   Error: contracts/ConvertLib.sol:2:1: ParserError: Source file requires different compiler version (current compiler is 0.5.6+commit.b259423e.Emscripten.clang - note that nightly builds are 
 ›   considered to be strictly less than the released version
 ›   library ConvertLib{
 ›   ^-----^
 ›
Compiling contract contracts/MetaCoin.sol... failed
```

**Context information**
- @cleanunicorn/mythos/0.8.0 darwin-x64 node-v10.15.3
- Mac OS Mojave 10.14.4

**Additional context**
MYTHX_ETH_ADDRESS and MYTHX_PASSWORD were exported with correct credentials

**Comment by cleanunicorn** [comment]
I was not able to compile the contracts with Solidity 0.4.0
