### ISSUE TITLE
[BUG] Error: Cannot use 'in' operator to search for

### ISSUE THREAD

**Issue by sjukeshov** [cleanunicorn/mythos#36]
**Describe the bug**
Error: Cannot use 'in' operator to search for

**To Reproduce**
1. https://github.com/ConsenSys/truffle-webpack-demo/blob/master/contracts/ConvertLib.sol
2. `mythos analyze contracts/ConvertLib.sol ConvertLib`
3. Error generated
 ›   Error: Cannot use 'in' operator to search for 'ConvertLib' in undefined

**Expected behavior**
Provide found issues, there should be SWC-103 at least

**Console output**
```
mythos analyze contracts/ConvertLib.sol ConvertLib
Reading contract contracts/ConvertLib.sol... done
Compiling with Solidity version: v0.4.0+commit.acd334c9
 ›   Error: Cannot use 'in' operator to search for 'ConvertLib' in undefined
Compiling contract contracts/ConvertLib.sol... failed
```

**Context information**
- @cleanunicorn/mythos/0.8.0 darwin-x64 node-v10.15.3
- Mac OS Mojave 10.14.4

**Additional context**
MYTHX_ETH_ADDRESS and MYTHX_PASSWORD were exported with correct credentials

**Comment by cleanunicorn** [comment]
I wasn't able to compile this locally with `solc`.
It works if you specify the solidity version, for example it works with:

```solidity
pragma solidity 0.5.8;
library Lib{}
```

**Comment by cleanunicorn** [comment]
It needs to find a contract, not only a library in the source code.
