### ISSUE TITLE
[BUG] Selected compiler version: vUnknown

### ISSUE THREAD

**Issue by sjukeshov** [cleanunicorn/mythos#37]
**Describe the bug**
little problem with provided Selected compiler version: **vUnknown**

**To Reproduce**
1. Analyze any contract with issue like https://smartcontractsecurity.github.io/SWC-registry/docs/SWC-100#visibility-not-setsol
2. for example above `mythos analyze contracts/visibility_not_set.sol HashForEther`
3. Error generated
Covered paths: 7
Selected compiler version: vUnknown

**Expected behavior**
v0.4.24

**Context information**
- @cleanunicorn/mythos/0.8.0 darwin-x64 node-v10.15.3
- Mac OS Mojave 10.14.4

**Comment by cleanunicorn** [comment]
This represents the `selectedCompiler` key from the JSON response. I removed the `v` prefix, but I still display `Unknown`.
