### ISSUE TITLE
[BUG]  ›  Error: Sources are provided without `mainSource` field

### ISSUE THREAD

**Issue by sjukeshov** [cleanunicorn/mythos#39]
**Describe the bug**
I tried to check Mythos with test contract https://smartcontractsecurity.github.io/SWC-registry/docs/SWC-100#visibility-not-setsol and getting this error on others also

**To Reproduce**
1. https://smartcontractsecurity.github.io/SWC-registry/docs/SWC-100#visibility-not-setsol
2. mythos analyze contracts/visibility_not_set.sol HashForEther
3. Error: Sources are provided without `mainSource` field

**Expected behavior**
SWC-100 detected

**Console output**
mythos analyze contracts/visibility_not_set.sol HashForEther
Reading contract contracts/visibility_not_set.sol... done
Compiling with Solidity version: v0.4.24+commit.e67f0147
(node:21429) V8: soljson-v0.4.24+commit.e67f0147.js:3 Invalid asm.js: Invalid member of stdlib
 ›   Warning: contracts/visibility_not_set.sol:18:30: Warning: Using contract member "balance" inherited from the address type is deprecated. Convert the contract to "address" type to access the member, 
 ›   for example use "address(contract).balance" instead.
 ›             msg.sender.transfer(this.balance);
 ›                                 ^----------^
 ›
 ›   Warning: contracts/visibility_not_set.sol:11:5: Warning: No visibility specified. Defaulting to "public". 
 ›        function withdrawWinnings() {
 ›        ^ (Relevant source part starts here and spans across multiple lines).
 ›
 ›   Warning: contracts/visibility_not_set.sol:17:6: Warning: No visibility specified. Defaulting to "public". 
 ›         function _sendWinnings() {
 ›         ^ (Relevant source part starts here and spans across multiple lines).
 ›
Compiling contract contracts/visibility_not_set.sol... done
Analyzing contract HashForEther... !
 ›   Error: Sources are provided without `mainSource` field

**Context information**
- Mythos version: @cleanunicorn/mythos/0.9.0 linux-x64 node-v11.14.0
- Node.js version: v11.14.0
- NPM version: 6.9.0
- OS type and version: Linux Ubuntu 16.04

**Additional context**

**Comment by cleanunicorn** [comment]
This was fixed in `0.10.0`.
