### ISSUE TITLE
unable to complete analysis due to internal error [BUG]

### ISSUE THREAD

**Issue by JoseMiguelHerrera** [cleanunicorn/mythos#41]
I'm running mythos analyze ./MyContract.sol MyContract and I get 

Reading contract ./MyContract.sol... done
Compiling with Solidity version: v0.4.25+commit.59dbf8f1
Compiling contract ./MyContract.sol... done
 ›   Error: Analysis failed: unable to complete analysis due to internal error
Analyzing contract MyContract... failed

I've tried with a couple different node versions and solidity compilers, and get the same thing. And yes I have the right mythX vars set up in my bash profile.

I'd love to get this tool working

**Comment by cleanunicorn** [comment]
Hello @JoseMiguelHerrera! The error that you're getting means that the error happened on the MythX API side. The tool was able to compile the contract and send the data but the API failed. :(

You should try again later, I know the people on the MythX side are constantly fixing bugs and making the platform more stable.
