### ISSUE TITLE
Doesn't work on macOS 10.14.6

### ISSUE THREAD

**Issue by PaulRBerg** [cleanunicorn/mythos#45]
**Describe the bug**
Cannot install with npm.

**Expected behavior**
I should be able to install mythos globally.

**Console output**

```bash
make: Entering directory '/Users/paulrberg/.nvm/versions/node/v10.15.3/lib/node_modules/@cleanunicorn/mythos/node_modules/sha3/build'
  CXX(target) Release/obj.target/sha3/src/addon.o
xcodebuild: error: SDK "macosx10.14" cannot be located.
g++: error: sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk macosx10.14 -find g++ 2> /dev/null' failed with exit code 16384: (null) (errno=No such file or directory)
g++: error: unable to find utility "g++", not a developer tool or in PATH
make: *** [sha3.target.mk:127: Release/obj.target/sha3/src/addon.o] Error 72
make: Leaving directory '/Users/paulrberg/.nvm/versions/node/v10.15.3/lib/node_modules/@cleanunicorn/mythos/node_modules/sha3/build'
```

[See the full error output in this gist](https://gist.github.com/PaulRBerg/503f0785d86e1c3ea27486a75dc2dbba).

**Context information**
- Node.js version: v10.15.3 (installed via nvm)
- NPM version: 6.11.3
- OS type and version: macOS 10.14.6

**Comment by PaulRBerg** [comment]
Nevermind, I had an issue with my `SDKROOT` environment variable.

[See this thread on StackOverflow for more details](https://stackoverflow.com/questions/51314888/ld-warning-text-based-stub-file-are-out-of-sync-falling-back-to-library-file/55344565#55344565).

**Comment by 8secz-johndpope** [comment]
catalina
export  SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk

**Comment by cleanunicorn** [comment]
@8secz-johndpope is this a fix for macOS?

If that's correct you can create a pull request to change the Readme.

**Comment by 8secz-johndpope** [comment]
yes - need to add ~/.zshrc or bash profile. 

It's a reflection of using different xcode / apple os not really concretely to do with mythos.

With Big Sur around the corner - 
export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.?.sdk
