### ISSUE TITLE
Use standard names for environment variables

### ISSUE THREAD

**Issue by b-mueller** [cleanunicorn/mythos#7]
Truffle Security and sabre both use the following naming convention:

```
MYTHX_ETH_ADDRESS
MYTHX_PASSWORD
```

It would be nice if we could standardize this so users don't have to set duplicate variables.

**Comment by b-mueller** [comment]
oops never mind, you're already using the same ones :)

**Comment by cleanunicorn** [comment]
My thoughts exactly :)
